#ifndef SUDOKU_INTERNAL_INTEL_CORE_14TH_DDR5_H
#define SUDOKU_INTERNAL_INTEL_CORE_14TH_DDR5_H

// Processors (Intel Core 14th Raptor Lake, i9-14900K)
#define SBDR_LOWER_BOUND_ 450  // 480
#define SBDR_UPPER_BOUND_ 800
#define REFRESH_CYCLE_LOWER_BOUND_ 500
#define REFRESH_CYCLE_UPPER_BOUND_ 1100
#define BANK_GROUP_THRESHOLD_ 500
#define REGULAR_REFRESH_INTERVAL_THRESHOLD_ 5500

#define PCI_OFFSET_UPPER_BOUND_ 0x0
#define PCI_OFFSET_LOWER_BOUND_ 0x0

#endif  // SUDOKU_INTERNAL_INTEL_CORE_14TH_DDR5_H
