#ifndef SUDOKU_INTERNAL_INTEL_CORE_12TH_DDR4_H
#define SUDOKU_INTERNAL_INTEL_CORE_12TH_DDR4_H

// Processors (Intel Core 12th Alder Lake, i9-12900K)
#define SBDR_LOWER_BOUND_ 450
#define SBDR_UPPER_BOUND_ 600
#define REFRESH_CYCLE_LOWER_BOUND_ 500
#define REFRESH_CYCLE_UPPER_BOUND_ 1000
#define BANK_GROUP_THRESHOLD_ 400  // for NUM_READ_STREAM (8) depends on offsets
#define REGULAR_REFRESH_INTERVAL_THRESHOLD_ 20000

#define PCI_OFFSET_UPPER_BOUND_ 0x0
#define PCI_OFFSET_LOWER_BOUND_ 0x0

#endif  // SUDOKU_INTERNAL_INTEL_CORE_12TH_DDR4_H
